### ISSUE TITLE
Unrecognized App. Please make sure you trust this app.

### ISSUE THREAD

**Issue by JaspreetDev1** [android-pay/androidpay-quickstart#11]
I built the app after adding the publicKey. When i tried running the app, i got this error
http://i.imgur.com/EHPfgJ3.jpg
"Unrecognized App. Please make sure you trust this app."

I'm new to this. Any help would be greatly appreciated.

**Comment by mariobat88** [comment]
Any luck with that problem?

**Comment by JaspreetDev1** [comment]
Change ENVIRONMENT_TEST to ENVIRONMENT_SANDBOX and hopefully It'll work. I didn't test it on this sample app but I was getting the same problem in a test app and It worked. Let me know if it works for you.

**Comment by mariobat88** [comment]
So I should use the ENVIRONMENT_SANDBOX that is deprecated?
And for the stripe PUBLISHABLE_KEY I should use the stripe live key?

**Comment by JaspreetDev1** [comment]
Yes, use the ENVIRONMENT_SANDBOX that is deprecated. You don't need to use stripe. Just use the public key that you generated yourself.

**Comment by mariobat88** [comment]
Yeah sorry I have to use stripe :) Thanks for the info

**Comment by JaspreetDev1** [comment]
You can use the Stripe key too. It won't make any difference except the latter decryption parts. You can still try changing the constant.

**Comment by mariobat88** [comment]
Just to make sure, I have to encrypt the publishable stripe key and set that value to the tokenization parameters?

**Comment by JaspreetDev1** [comment]
You don't need to encrypt the key. Just take the live key from your Stripe account and set it in PaymentMethodTokenizationParameters

**Comment by mariobat88** [comment]
Ok, thanks.

**Comment by mariobat88** [comment]
I added the ENVIRONMENT_SANDBOX, but now I get the resultcode = 1, which is RESULT_FIRST_USER, and I get an errorCode 8. Did you have a problem with that or do you know what could cause the problem?

**Comment by Kai2k** [comment]
I do not believe this is an issue. You should use ENVIRONMENT_TEST. In development, you will always receive this error, as Google state here: https://developers.google.com/android-pay/get-started#step_2
Here, they say the following: Note: Our test environment will not return live, chargeable tokens in the FullWallet response, but will allow us to test your pre-purchase flow. You will see an Unrecognized App error on the Android Pay chooser until your app has production access.

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.

**Comment by Paras247** [comment]
I have same error. I am using payeezy for AndroidPAY. so i generate AndroidPay in Live.  Where to add CSR / Public Key after download. For Live which Environment use? ENVIRONMENT_PRODUCTION..???

I want to Add Android Pay in live
Please help me
