### ISSUE TITLE
Android Pay credit cards

### ISSUE THREAD

**Issue by jponsc** [android-pay/androidpay-quickstart#12]
I am developing a mobile android app and I'm interested in using Android Pay APIs. I am currently using the android pay sample app from GitHub. However, my credit cards are not from one of the participating banks with Android Pay.
I'd like to add some "fake" / sandbox credit cards to my Android Pay account. Does anyone know of any test/sandbox credit card accounts I can add/use with Android Pay? Thank you.

**Comment by mithilwcities** [comment]
https://github.com/android-pay/androidpay-quickstart/issues/6#issuecomment-164699917

**Comment by 8of** [comment]
@jponsc 
Tested myself:
1. Install Android Pay app on your device
2. Turn on Sandbox Mode by executing following commands (line by line) from command prompt:
```
adb shell
cd /sdcard/Download;
rm ­-f android_pay_env_override_*;
touch android_pay_env_override_sandbox;
```
Watch out for line three - for some reason when copy-paste this line it adds one more "-" symbol before **f** (at least on macOS).

3. Restart the phone
4. Launch the Android Pay app and add following test credit card details:
```
Card Number: 4622 9431 2999 9901
Expiry: 12/17
CVV: 213
```
5. Enter other details like address and proceed.
_Card is added successfully._
6. Use WalletConstants.ENVIRONMENT_SANDBOX to integrate and test Android Pay in your app (constant marked as Deprecated).
7. Revert from Sandbox to Production by executing following commands from command prompt:
```
adb shell
cd /sdcard/Download;
rm -­f android_pay_env_override_*;
```
Again< look for additional "-" symbol before **f**.
8. Restart phone
9. Use ENVIRONMENT_PRODUCTION or ENVIRONMENT_TEST with your real card to integrate and test Android Pay in your app. You should not be charged with ENVIRONMENT_TEST constant.

Taken from:
https://stackoverflow.com/a/39656094/2190175

**Comment by NULL00000000** [comment]
080 0091 091

**Comment by devendroid** [comment]
Hi @8ofproject, @jponsc ,
After successfully executed the command and restart the phone, I tried above card detail but getting "Your card couldn't be added
Please contact your card issuer for more info. You can also try adding a different card." 
What I'm doing wrong ?

**Comment by dreamstar725** [comment]
I also got the issue message.
This post is fake.

**Comment by 8of** [comment]
@devsideal @dreamstar725 Does Android Pay service officially support your country?

**Comment by devsideal** [comment]
Finally, I have successfully added the card just skip the 3rd step means don't restart the phone and its working.

**Comment by devendroid** [comment]
No, not supported for India.

**Comment by NULL00000000** [comment]
但他的臉蛋超人回來的時候

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.

**Comment by swetanandha** [comment]
@devsideal 
Is there any solution for india?

**Comment by swetanandha** [comment]
@devsideal 
My client need Android pay for his app
Now what I need to do from my end?
How we can test it?

**Comment by devendroid** [comment]
@swetanandha 
I didn't get any solution to test in India, so finally i stoped my RND for android pay and switch to Google payment as suggested by Google Support Team also,
..........
https://developers.google.com/payments
We’re excited to announce the arrival of our new Google Payment API, which will replace the Android Pay API.
The Google Payment API will provide an even more seamless checkout experience within your app or mobile web for Android users!
Due to this change, we will no longer be supporting new Android Pay integrations or launches.  Please visit our developer docs for more information and how to get started on the integration process for the new API.
