### ISSUE TITLE
wrong request code if SupportWalletFragment replace in fragment view conteiner

### ISSUE THREAD

**Issue by Kesedi** [android-pay/androidpay-quickstart#14]
I have some problem with this question:
http://stackoverflow.com/questions/36444972/replase-supportwalletfragment-on-fragment-view-id-return-wrong-request-code

Is it a bug or I am doing something wrong?

**Comment by 8of** [comment]
You should call super.**onActivityResult** from you activity's **onActivityResult** before anything else.
_That's basically what the answer on stackoverflow told you to do._

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.
