### ISSUE TITLE
Address check in PromoAddressLookupFragment.java no longer works

### ISSUE THREAD

**Issue by evanfeller** [android-pay/androidpay-quickstart#16]
The UserAddressRequest now returns with a result code of 1 and does not populate the address dialogue like it used too.

**Comment by evanfeller** [comment]
So this problem only occurs when using the Address.API in android M, when tested in L and on a beta N device the api works like a charm and lets me choose a UserAddress object form the dialog

**Comment by samtstern** [comment]
@fellere thank you for the report, and then the detailed follow up. I will take a look.

**Comment by 8of** [comment]
Error gone away.
Tried several countries, several addresses in several languages (just in case). No error in sight.
Tested on real device 6.0.1 and Emulator.

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.
