### ISSUE TITLE
Wallet.Payments.loadFullWallet errorCode is 8 and resultCode is 1

### ISSUE THREAD

**Issue by jerrycho** [android-pay/androidpay-quickstart#23]
Hi,

I want to  add google pay at my app that I am try to build up the the sample code for testing.

Overall ok. but when I am trying loadFullWallet. the errorcode is 8 and result code is 1 on onActivityResult

Anyone can help me, many thanks

**Comment by samtstern** [comment]
@jerrycho we'll need some more information for debugging.  Can you provide `logcat` output?  Is this happening during the sign-in phase?  If so, have you configured your SHA1 correctly?

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.
