### ISSUE TITLE
Issue in generating hex key for android pay

### ISSUE THREAD

**Issue by pavithraJayanna** [android-pay/androidpay-quickstart#25]
Hi I am trying to use android pay . publicly and private key is generated for me using genkey.sh
Where I need to assign the PUBLICKEY value to generated public  key.

While running the following command , I am getting error saying  'xxd' is not recognized as an internal or external command,
operable program or batch file.
echo $PUBLICKEY | xxd -r -p | base64

**Comment by 8of** [comment]
@pavithraJayanna 
1. You need to copy-paste `echo $PUBLICKEY | xxd -r -p | base64` to some code editor.
2. Copy everything between **pub:** and **ASN1** and replace **$PUBLICKEY** with it
3. Remove extra new-lines. It will be very long one line.
4. Copy-paste the line from editor to terminal and execute it
5. Copy output result string and paste it to ids.xml according to guide.

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.
