### ISSUE TITLE
Not to able to find Android Pay button

### ISSUE THREAD

**Issue by jhalagaiah** [android-pay/androidpay-quickstart#26]
![screenshot_20170321-001927](https://cloud.githubusercontent.com/assets/26407439/24132526/2bfa7862-0e1c-11e7-8e01-05a56bc818b2.png)

I have installed androidpay-quickstart (Awesome bike store) application and I am not able to find "Buy with Android Pay" button. I have attached the screenshot for the same.
I have installed Android pay app on my device. 

Kindly let me know if I am missing anything and guide me with sample card information for testing the app.

**Comment by samtstern** [comment]
@jhalagaiah do you have a valid credit card set up in the Android pay app?  Normally this screen is a result of not being "ready to pay" with AP which means either not having the app or not being fully set up in the app.

**Comment by jhalagaiah** [comment]
@samtstern 
I have added a card details (Sandboxed) to Android Pay app. Attached is the screen shot.
![screenshot_20170322-002712](https://cloud.githubusercontent.com/assets/26407439/24182250/8299a9b6-0ee6-11e7-84d3-088edae3a67d.png)

For sandbox procedure, I have used the instructions given in below link:
http://stackoverflow.com/questions/34020432/android-pay-testing-from-outside-us#

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.
