### ISSUE TITLE
Building project is failing

### ISSUE THREAD

**Issue by suvansh-dev** [android-pay/androidpay-quickstart#33]
Hi,
The project is not building up, anyone facing the same issue?

**Comment by samtstern** [comment]
@suvansh-dev I just did a fresh `git clone` of this sample and then ran `./gradlew :app:assembleDebug` and it all built successfully so I don't believe there is a problem.  Can you describe your issue?

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.
