### ISSUE TITLE
Merchnant Specific flow not implemented

### ISSUE THREAD

**Issue by gowthamidommeti** [android-pay/androidpay-quickstart#35]
When I click on checkout it displaying the toast message like...

       Not implemented.Merchant specific payment Flow.

What I do to perform the checkout.

**Comment by tanseerpasha** [comment]
Even I am facing this issue, 
When I click on checkout it displaying the toast message like...
   Not implemented.Merchant specific payment Flow.
What I do to perform the checkout.

**Comment by tanseerpasha** [comment]
When I click on checkout it displaying the toast message like...

   Not implemented.Merchant specific payment Flow.
What I do to perform the checkout.

**Comment by tanseerpasha** [comment]
Even I am facing above issue. 

```
private void continueCheckout() {
        Toast.makeText(this, R.string.checkout_bikestore_message, Toast.LENGTH_LONG).show();
    }
```
what changes we need to do?

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.
