### ISSUE TITLE
loadFullWallet returns error 10 if upgrade library version to 8.3.0

### ISSUE THREAD

**Issue by lukicmarko** [android-pay/androidpay-quickstart#8]
- compile 'com.google.android.gms:play-services-plus:8.3.0'
- compile 'com.google.android.gms:play-services-wallet:8.3.0'

**Comment by samtstern** [comment]
I don't know of an error code '10' that has to do with Android Pay (https://developers.google.com/android/reference/com/google/android/gms/wallet/WalletConstants).

There is `CommonStatusCodes.DEVELOPER_ERROR` with that value (https://developers.google.com/android/reference/com/google/android/gms/common/api/CommonStatusCodes) which means the app has been misconfigured in some way.  You should look at the output of `adb logcat` in your terminal to see what messages are printed around the time of the error.

**Comment by samtstern** [comment]
Thank you for taking the time to submit this issue, and I apologize that we never got around to solving it. I am closing this issue because the Android Pay API has been superseded by the Google Payments API.

This sample is deprecated and is no longer maintained. Please see the [paymentsapi-quickstart](https://github.com/android-pay/paymentsapi-quickstart) sample for an up-to-date sample.

If you believe your issue is relevant to that sample as well, please feel free to open a new issue there and we can continue discussing.

**Comment by lukicmarko** [comment]
Thanks.
